name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
jobs:  
  build:
    runs-on: ubuntu-latest  
    steps:    
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Connect to bastion host
        env:
          PRIVATE_KEY: ${{ secrets.BASTION_PRIVATE_KEY  }}
        run: |
          echo "$BASTION_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@100.25.109.4
          script: |
            /home/ec2-user/backend.sh
